services:
  database:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ROOT
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ROOT
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - database

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    depends_on:
      - database

  backend:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://ROOT:1234@database:5432/ROOT
    volumes:
      - ./server:/app
    ports:
      - "5000:3000"
    depends_on:
      - database
    networks:
      - backend


networks:
  backend:

volumes:
  db-data:
  pgadmin-data:
